# Generated by Django 3.2.8 on 2021-10-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(default=1)),
                ('countries_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketApp.countries')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(blank=True, max_length=100, null=True)),
                ('born_date', models.DateField(null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('career_score', models.IntegerField(default=0)),
                ('player_role', models.CharField(blank=True, choices=[('Batting', 'Batting'), ('Bowling', 'Bowling'), ('Batting/Wk', 'Batting/Wk')], max_length=100, null=True)),
                ('batting_style', models.CharField(blank=True, max_length=100, null=True)),
                ('bowling_style', models.CharField(blank=True, max_length=100, null=True)),
                ('icc_ranking', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(default=1)),
                ('team_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketApp.teams')),
            ],
        ),
    ]
