# Generated by Django 3.2.8 on 2021-10-28 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketApp', '0002_playerprofile_palyer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerprofile',
            old_name='palyer_image',
            new_name='player_image',
        ),
    ]
