# Generated by Django 3.2.8 on 2021-10-28 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketApp', '0004_alter_playerprofile_team_id_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='team_id_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketApp.teams'),
        ),
    ]
