# Generated by Django 3.2.8 on 2021-10-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketApp', '0005_alter_playerprofile_team_id_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stadium_name', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(default=1)),
            ],
        ),
    ]
