# Generated by Django 3.2.8 on 2021-10-28 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketApp', '0006_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(null=True)),
                ('match_time', models.TimeField(null=True)),
                ('match_status', models.CharField(default='not_complete', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(default=1)),
                ('Venue_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketApp.venue')),
                ('team_id1_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='cricketApp.teams')),
                ('team_id2_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='cricketApp.teams')),
            ],
        ),
    ]
