# Generated by Django 3.2.8 on 2021-10-28 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketApp', '0007_matchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchSummery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(default=1)),
                ('best_fielder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_fielder', to='cricketApp.playerprofile')),
                ('bowler_ofthe_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowler_ofthe_match', to='cricketApp.playerprofile')),
                ('looser_team_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looser_team', to='cricketApp.teams')),
                ('man_ofthe_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='man_ofthe_match', to='cricketApp.playerprofile')),
                ('matchlist_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketApp.matchlist')),
                ('winner_team_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_team', to='cricketApp.teams')),
            ],
        ),
    ]
