# Generated by Django 3.2.8 on 2021-10-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricketApp', '0008_matchsummery'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentScoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_match_count', models.IntegerField(default=0)),
                ('winning_count', models.IntegerField(default=0)),
                ('losses_count', models.IntegerField(default=0)),
                ('net_run_ret', models.FloatField(default=0.0)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.IntegerField(default=1)),
                ('team_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketApp.teams')),
            ],
        ),
    ]
