# Generated by Django 3.2.8 on 2021-10-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketApp', '0009_tournamentscoremodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='losses_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='net_run_ret',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='teams',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='total_match_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='winning_count',
            field=models.IntegerField(default=0),
        ),
    ]
